### ISSUE TITLE
Checklist for Java 8 as minimum version

### ISSUE THREAD

**Issue by dannil** [dannil/scb-java-client#82]
The list below shows a summary of the tasks which needs to be completed before we increment the minimum required Java version. The branch designated for being the mainline for Java 8 minimum version is *enh/java-8-minimum*.

- [x] **Update maven-compiler-plugin**
Source and target properties needs to be updated to reflect Java 8 support and requirement.

- [x] **Upgrade Checkstyle to 7.x**
Or the newest version supporting Java 8.

- [x] **Upgrade animal-sniffer-maven-plugin to use Java 8 signature**
This is trivial; all we need to do is update the signature artifact.
```xml
<artifactId>java17</artifactId>
```
becomes
```xml
<artifactId>java18</artifactId>
```
- [x] **Use new Date and Time API for DateJUnitRunner**
This is being developed in branch *enh/java-8/datejunitrunner*.

- [x] **Update README to reflect Java 8 as minimum version**

**Comment by dannil** [comment]
Java 9 isn't released yet as of today's release of 0.5.0: moving issue to release 0.6.0

**Comment by dannil** [comment]
Closed by #89
